# -*- coding: utf-8 -*-
"""ResumeAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Etyun62ioCbK3_ypna-CJ-m7EyCoMp92
"""

import os
from dotenv import load_dotenv
from langchain_community.tools import WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper
from langchain_community.tools import DuckDuckGoSearchRun
from langchain.agents import create_agent
from langchain.agents.middleware import ToolRetryMiddleware,ModelRetryMiddleware
from langchain_core.tools import tool
from langchain_community.document_loaders import PyPDFLoader
from langchain_core.messages import SystemMessage, HumanMessage
from pydantic import BaseModel, Field
import tempfile
import streamlit as st
load_dotenv()
gemini_key = (
    os.getenv('GEMINI_API_KEY')
    or os.getenv('GOOGLE_API_KEY')
    or os.getenv('Geminii')
    or os.getenv('geminii')
)
if gemini_key:
    os.environ['GOOGLE_API_KEY'] = gemini_key
else:
    raise RuntimeError(
        'Gemini API key required. Set GEMINI_API_KEY, GOOGLE_API_KEY, or Geminii in .env or your environment.'
    )
llm="google_genai:gemini-2.5-flash-lite"
search=DuckDuckGoSearchRun()
wikipedia = WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())

sked_agent = create_agent(
    model=llm,
    tools= [wikipedia],
    middleware=[
        ModelRetryMiddleware(max_retries=3),
        ToolRetryMiddleware(
           max_retries=3,
           retry_on=(ConnectionError, TimeoutError) ,
        ),
           ],
    system_prompt = """
    You are a resume evaluation assistant focused on skills and education matching.

    Use Wikipedia only when it helps verify broad skill/discipline context, not for opinion or speculative judgments.

    Task:
    - Compare resume skills and education with the job description.
    - Extract explicit matches, missing skills, and education relevance.
    - Be concise, factual, and structured.

    Return format:
    MATCH: XX%
    MISSING: [list]
    RATING: X/10
    NOTES: short explanation
    """
    )


exp_agent = create_agent(
    model=llm,
    tools= [search],
       middleware=[
        ModelRetryMiddleware(max_retries=3),
        ToolRetryMiddleware(
           max_retries=3,
           retry_on=(ConnectionError, TimeoutError) ,
        ),
           ],
    system_prompt = """
    You are a resume evaluation assistant focused on work experience matching.

    Use web search only for public market or role-context references when needed.
    Do not invent experience. Only infer from the resume and job description.

    Task:
    - Compare years of experience, role alignment, seniority, and domain fit.
    - Highlight relevant companies, titles, and scope.
    - Return a concise experience fit summary.

    Return format:
    FIT: XX%
    COMPANIES: [list]
    ROLES: [list]
    RATING: X/10
    NOTES: short explanation
    """
    )


sal_agent = create_agent(
    model=llm,
    tools= [search],
       middleware=[
        ModelRetryMiddleware(max_retries=3),
        ToolRetryMiddleware(
           max_retries=3,
           retry_on=(ConnectionError, TimeoutError) ,
        ),
           ],
    system_prompt = """
    You are a compensation research assistant.

    Use web search only for public salary-market context.
    Do not guess salary. If exact salary data is unavailable, provide an estimated range and clearly label it as an estimate.

    Task:
    - Estimate market-aligned salary range for the role, location, and years of experience.
    - Mention confidence level and whether the profile seems above, below, or aligned with the market.

    Return format:
    RANGE: X - Y LPA
    PERCENTAGE HIKE: XX%
    CONFIDENCE: LOW/MEDIUM/HIGH
    NOTES: short explanation
    """
    )

@tool
def call_skill_edu_matcher(resume: str, job_desc: str) -> str:
    """Analyze skill and education fit between resume and job description."""
    response = sked_agent.invoke({
        "messages": [
            HumanMessage(content=f"""
    Resume:
    {resume}

    Job Description:
    {job_desc}

    Evaluate skill and education fit only.
    """)
    ]
    })
    return response["messages"][-1].content

@tool
def call_exp_matcher(resume_exp: str, job_role: str) -> str:
    """Analyze work experience fit for the role."""
    response = exp_agent.invoke({
        "messages": [
              HumanMessage(content=f"""
  Resume Experience:
  {resume_exp}

  Target Role:
  {job_role}

  Evaluate experience fit only.
  """)
          ]
      })
    return response["messages"][-1].content

@tool
def call_sal_matcher(role: str, location: str, years: float) -> str:
    """Research salary alignment for role, location, and years of experience."""
    response = sal_agent.invoke({
        "messages": [
            HumanMessage(content=f"""
Role: {role}
Location: {location}
Years of Experience: {years}

Estimate market salary alignment.
""")
        ]
    })
    return response["messages"][-1].content

class ResumeDecision(BaseModel):
    decision: str = Field( description="APPROVE or REJECT")
    score: int = Field( description="Overall Score from 0 to 100")
    summary: str = Field( description="Short recruiter-style summary ")
    skill_fit: str = Field( description="Skill and education fit analysis")
    experience_fit: str = Field( description="Work experience fit analysis")
    salary_alignment: str = Field( description="Salary-market alignment analysis")
sup_agent = create_agent(
    model = llm,
    tools = [call_skill_edu_matcher, call_exp_matcher, call_sal_matcher],
    system_prompt = '''
    You are a senior recruiting manager screening resumes for shortlisting.

    Workflow:
    1. Evaluate skill and education fit first.
    2. Evaluate experience fit second.
    3. Evaluate salary-market alignment third.
    4. Make a final decision only after reviewing all three signals.
    5. Never call any tool other than the three tools listed above.

    Decision rules:
    - APPROVE if skills are strong, experience is relevant, and compensation seems aligned.
    - REJECT if core requirements are missing or experience is too far from the role.
    - Use a score from 0 to 100.
    - Be strict, realistic, and concise.

    Output a structured final decision only.
    '''
)

def extract_text_from_upload (uploaded_file):
    if uploaded_file is not None:
        with tempfile.NamedTemporaryFile(delete=False) as tmp_file:
            tmp_file.write(uploaded_file.getvalue())
            tmp_file_path = tmp_file.name
        try:
            loader = PyPDFLoader(tmp_file_path)
            documents = loader.load()
            text = "\n".join([doc.page_content for doc in documents])
            return text
        finally:
            if os.path.exists(tmp_file_path):
                os.remove(tmp_file_path)
        
st.title("Resume Analyzer")
uploaded_resume = st.file_uploader("Upload Resume (PDF)", type=["pdf"])
uploaded_job_desc = st.file_uploader("Upload Job Description (PDF)", type=["pdf"])
if uploaded_resume and uploaded_job_desc:
    if st.button("evaluate"):
        resume_text = extract_text_from_upload(uploaded_resume)
        job_desc_text = extract_text_from_upload(uploaded_job_desc)
        response = sup_agent.invoke({'messages': [
            HumanMessage(
                f''' Analyze the given resume {resume_text} with job description {job_desc_text}'''
            )
        ]})
        st.subheader("Evaluation Result")
        st.json(response['messages'][-1].content)